version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dog-eared-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15mjditwhtva0"
s3_prefix = "sam-app"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

