AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  dog-eared-sam

Globals:
  Function:
    Runtime: nodejs12.x

Parameters:
  GraphQLURI:
    Type: String

Resources:
  # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  StartQuotedTweetsImport:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: startQuotedTweetsImport
      CodeUri: functions/import-quoted-tweets/dist
      Handler: bundle.startQuotedTweetsImport
      Role:
        Fn::Sub: "arn:aws:iam::${AWS::AccountId}:role/start-quoted-tweets-import"
      Environment:
        GRAPHQL_URI:
          Ref: GraphQLURI
        QUOTED_TWEETS_IMPORT_QUEUE_URL:
          Fn::Sub: "https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/dog-eared-import-quoted-tweets"
  ImportQuotedTweets:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: importQuotedTweets
      CodeUri: functions/import-quoted-tweets/dist
      Handler: bundle.importQuotedTweets
      ReservedConcurrentExecutions: 2
      Role:
        Fn::Sub: "arn:aws:iam::${AWS::AccountId}:role/import-quoted-tweets"
      Environment:
        GRAPHQL_URI:
          Ref: GraphQLURI

Outputs:
  StartQuotedTweetsImportArn:
    Description: "StartQuotedTweetsImport function ARN"
    Value: !Ref StartQuotedTweetsImport
  ImportQuotedTweets:
    Description: "ImportQuotedTweets function ARN"
    Value: !Ref ImportQuotedTweets
