service:
  name: serverless
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  appName: dog-eared
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-pseudo-parameters

provider:
  name: aws
  stage: ${opt.stage, 'prod'}
  region: ${opt:region, 'ap-northeast-1'}
  stackName: dog-eared-serverless
  runtime: nodejs12.x
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  deploymentBucket:
    name: code.${env:BASE_DOMAIN_NAME}
  deploymentPrefix: ${self:custom.appName}/serverless/

functions:
  startQuotedTweetsImport:
    name: ${self:custom.appName}-start-quoted-tweets-import
    handler: handler.startQuotedTweetsImport
    role: "arn:aws:iam::#{AWS::AccountId}:role/start-quoted-tweets-import"
    timeout: 15
    environment:
      GRAPHQL_URI: ${env:GRAPHQL_URI}
      IMPORT_QUOTED_TWEETS_QUEUE_URL: "https://sqs.#{AWS::Region}.amazonaws.com/#{AWS::AccountId}/${self:custom.appName}-import-quoted-tweets"
  importQuotedTweets:
    name: ${self:custom.appName}-import-quoted-tweets
    handler: handler.importQuotedTweets
    role: "arn:aws:iam::#{AWS::AccountId}:role/import-quoted-tweets"
    timeout: 300
    environment:
      GRAPHQL_URI: ${env:GRAPHQL_URI}
    events:
      - sqs:
          arn: "arn:aws:sqs:#{AWS::Region}:#{AWS::AccountId}:${self:custom.appName}-import-quoted-tweets"
