name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_DB: dog_eared_test
        ports:
          # will assign a random free host port
          - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Cache ~/.sbt
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt
      - name: Cache ~/.ivy2
        uses: actions/cache@v1
        with:
          path: ~/.ivy2
          key: ${{ runner.os }}-ivy2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Run tests
        run: sbt 'project drivenAdapters' 'Test / flywayMigrate' 'project tests' test
        env:
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
